# Generated by Django 5.0.14 on 2026-07-21 16:04

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='organization_logos/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number (digits, spaces, +, -, and parentheses only).', regex='^\\+?[0-9\\s\\-()]{7,20}$')]),
        ),
    ]
