# Generated by Django 5.0.14 on 2026-08-08 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_demo_user_must_reset_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
