# Generated by Django 5.0.14 on 2026-09-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_narration_language',
            field=models.CharField(choices=[('en', 'English'), ('ne', 'Nepali')], default='en', max_length=5),
        ),
    ]
