# Generated by Django 5.0.14 on 2026-09-05 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_preferred_narration_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assessment_level',
            field=models.CharField(blank=True, choices=[('assistant_supervisor', 'Assistant/Supervisor'), ('officer', 'Officer'), ('management', 'Management'), ('senior_management', 'Senior Management')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='branch_department',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='corporate_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='functional_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
