# Generated by Django 5.0.14 on 2026-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_assessment_level_user_branch_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='assessment_level',
            field=models.CharField(blank=True, choices=[('assistant_supervisor', 'Front-Line Level'), ('officer', 'Officer Level'), ('management', 'Middle Management Level'), ('senior_management', 'Top Management Level')], max_length=30, null=True),
        ),
    ]
