# Generated by Django 5.0.14 on 2026-09-12 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_assessment_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='current_streak_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_active_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
