# Generated by Django 5.0.14 on 2026-09-29 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_current_streak_days_user_last_active_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='path_overdue_reminder_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='reminder_exempt',
            field=models.BooleanField(default=False),
        ),
    ]
