"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.0.14.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-+^gh7!0eaq!brkfea7-poa*(jckjk#(l%@w)a8d-iki!6e0@c$')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False') == 'True'

# Comma-separated in production, e.g. ALLOWED_HOSTS=api.example.com,www.example.com
ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'storages',
    'accounts',
    'courses',
    'assessments',
    'assignments',
    'scenarios',
    'gamification',
    'certificates',
    'audit',
    'dialogue',
    'narration',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Explicit allowlist only — never enable CORS_ALLOW_ALL_ORIGINS in production.
# Set the CORS_ALLOWED_ORIGINS env var (comma-separated) in production, e.g.
# CORS_ALLOWED_ORIGINS=https://app.example.com,https://admin.example.com
# Falls back to the local Vite dev ports when unset.
CORS_ALLOW_ALL_ORIGINS = False
_cors_env_origins = [o.strip() for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o.strip()]
CORS_ALLOWED_ORIGINS = _cors_env_origins or ['http://localhost:5173', 'http://localhost:5174']

# Required by Django for cross-origin POSTs (e.g. the Django admin, browsable
# API) once served over HTTPS with a real domain. Reuses the CORS allowlist
# above since it's the same set of trusted frontend origins.
CSRF_TRUSTED_ORIGINS = _cors_env_origins

AUTH_USER_MODEL = 'accounts.User'

# Base URL used to build the certificate verification link encoded in the QR code.
CERTIFICATE_VERIFICATION_BASE_URL = os.environ.get('CERTIFICATE_VERIFICATION_BASE_URL', 'http://localhost:8000')

# Base URL of the React app, used to build the login link sent in demo-user
# invite emails (accounts.services.send_demo_user_invite_email) — the backend
# has no other way to know the frontend's origin.
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:5173')

# Claude (script generation) and Azure Neural TTS (audio synthesis) for
# narration.services.generate_slide_narration — read entirely from the
# environment, never hardcoded. Left blank in dev is fine: generation just
# raises NarrationGenerationError until they're set.
ANTHROPIC_API_KEY = os.environ.get('ANTHROPIC_API_KEY', '')
AZURE_SPEECH_KEY = os.environ.get('AZURE_SPEECH_KEY', '')
AZURE_SPEECH_REGION = os.environ.get('AZURE_SPEECH_REGION', '')

# SMTP credentials read entirely from the environment — never hardcoded. Only
# ever set EMAIL_HOST_PASSWORD via .env (gitignored) locally or the host's
# environment-variable UI in production.
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.environ.get('EMAIL_HOST', '')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
# Mutually exclusive per Django's own check — SSL (typically port 465) is only
# used if explicitly requested; TLS (typically port 587) is the default.
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False') == 'True'
_email_use_tls_env = os.environ.get('EMAIL_USE_TLS')
EMAIL_USE_TLS = (_email_use_tls_env == 'True') if _email_use_tls_env is not None else not EMAIL_USE_SSL
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'webmaster@localhost')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
    # No blanket throttle — only endpoints that opt in via throttle_scope
    # (login, quiz submission) are rate-limited. See SECURITY.md.
    'DEFAULT_THROTTLE_CLASSES': (
        'rest_framework.throttling.ScopedRateThrottle',
    ),
    'DEFAULT_THROTTLE_RATES': {
        'login': '10/min',
        'quiz-submit': '20/min',
    },
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
}

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
#
# DB_ENGINE picks the backend: 'postgresql' (default, for local dev) or
# 'mysql' (cPanel hosting only offers MySQL — see the audit that preceded
# this switch: nothing in the codebase uses django.contrib.postgres or any
# other Postgres-only feature, so this is a safe env-var toggle rather than
# a real migration effort).

DB_ENGINE = os.environ.get('DB_ENGINE', 'postgresql')

_DB_ENGINE_BACKENDS = {
    'postgresql': 'django.db.backends.postgresql',
    'mysql': 'django.db.backends.mysql',
}
_DB_ENGINE_DEFAULT_PORTS = {
    'postgresql': '5432',
    'mysql': '3306',
}

if DB_ENGINE not in _DB_ENGINE_BACKENDS:
    raise ImproperlyConfigured(f"DB_ENGINE must be 'postgresql' or 'mysql', got {DB_ENGINE!r}.")

DATABASES = {
    'default': {
        'ENGINE': _DB_ENGINE_BACKENDS[DB_ENGINE],
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', _DB_ENGINE_DEFAULT_PORTS[DB_ENGINE]),
    }
}

if DB_ENGINE == 'mysql':
    # utf8mb4 (not MySQL's default 3-byte utf8) is required for full Unicode,
    # including the emoji stored in gamification.Badge.icon.
    DATABASES['default']['OPTIONS'] = {'charset': 'utf8mb4'}


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {'min_length': 8},
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
    {
        'NAME': 'accounts.validators.LetterAndDigitPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# Media files (user uploads)
# https://docs.djangoproject.com/en/5.0/topics/files/

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Set USE_S3=True in .env to switch uploads to AWS S3 via django-storages.
# AWS credentials/bucket are read from env vars but are not configured yet —
# leave USE_S3=False for local development, which uses the filesystem above.
USE_S3 = os.environ.get('USE_S3', 'False') == 'True'

# WhiteNoise's compressed+manifest storage depends on the manifest file
# collectstatic writes into STATIC_ROOT, so it's only safe once that's
# actually been run — production only. Under DEBUG, runserver keeps serving
# static files itself (via django.contrib.staticfiles' finders) regardless
# of this setting, so local dev is unaffected either way.
_staticfiles_backend = (
    'django.contrib.staticfiles.storage.StaticFilesStorage'
    if DEBUG
    else 'whitenoise.storage.CompressedManifestStaticFilesStorage'
)

if USE_S3:
    AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID', '')
    AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY', '')
    AWS_STORAGE_BUCKET_NAME = os.environ.get('AWS_STORAGE_BUCKET_NAME', '')
    AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
    AWS_S3_CUSTOM_DOMAIN = os.environ.get('AWS_S3_CUSTOM_DOMAIN', '')
    AWS_DEFAULT_ACL = None
    AWS_S3_FILE_OVERWRITE = False
    AWS_QUERYSTRING_AUTH = False

    STORAGES = {
        'default': {
            'BACKEND': 'storages.backends.s3boto3.S3Boto3Storage',
        },
        'staticfiles': {
            'BACKEND': _staticfiles_backend,
        },
    }
else:
    STORAGES = {
        'default': {
            'BACKEND': 'django.core.files.storage.FileSystemStorage',
        },
        'staticfiles': {
            'BACKEND': _staticfiles_backend,
        },
    }


# Production security hardening (HTTPS-only cookies, HSTS, SSL redirect).
# Skipped under DEBUG so local http://localhost dev isn't broken — see SECURITY.md.
if not DEBUG:
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_HTTPONLY = True
    SESSION_COOKIE_SAMESITE = 'Lax'
    CSRF_COOKIE_SAMESITE = 'Lax'

    SECURE_SSL_REDIRECT = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_BROWSER_XSS_FILTER = True

    SECURE_HSTS_SECONDS = 60 * 60 * 24 * 30  # 30 days; raise once HTTPS rollout is confirmed stable
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    # Trust the X-Forwarded-Proto header from the load balancer/reverse proxy
    # when determining whether the original request was HTTPS.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
