# Generated by Django 5.0.14 on 2026-09-14 11:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_user_current_streak_days_user_last_active_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_per_attempt', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('seconds_per_question', models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)])),
                ('pass_mark_percent', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='accounts.organization')),
            ],
        ),
    ]
