# Generated by Django 5.0.14 on 2026-09-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_settings', '0002_seed_org_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='logged_in_inactive_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='logged_in_inactive_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='logged_in_inactive_reminder_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='never_logged_in_last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='never_logged_in_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='never_logged_in_reminder_frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('monthly', 'Monthly')], default='weekly', max_length=20),
        ),
    ]
