# Generated by Django 5.0.14 on 2026-09-15 03:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_settings', '0003_organizationsettings_logged_in_inactive_last_sent_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='timing_mode',
            field=models.CharField(choices=[('PER_QUESTION', 'Per question'), ('FIXED_TOTAL', 'Fixed total for the exam')], default='PER_QUESTION', max_length=20),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='total_exam_minutes',
            field=models.PositiveIntegerField(default=60, validators=[django.core.validators.MinValueValidator(5)]),
        ),
    ]
