# Generated by Django 5.0.14 on 2026-09-15 06:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_settings', '0004_organizationsettings_timing_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='max_course_retake_attempts',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='max_level_assessment_attempts',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
