# Generated by Django 5.0.14 on 2026-09-29 06:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_settings', '0006_derive_question_time_from_exam_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='max_active_learners',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='org_admin_grace_period_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='path_overdue_months_after_enrollment',
            field=models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='path_overdue_reminder_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='path_overdue_repeat_days',
            field=models.PositiveIntegerField(default=7, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='subscription_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='organizationsettings',
            name='subscription_start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
