# Generated by Django 5.0.14 on 2026-10-09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_settings', '0007_organizationsettings_max_active_learners_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationsettings',
            name='max_quiz_attempts',
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
