# Generated by Django 5.0.14 on 2026-09-05 15:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_user_assessment_level_user_branch_department_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('marks', models.PositiveIntegerField(default=1)),
                ('explanation', models.TextField(blank=True, help_text='Rich text shown to the learner after answering.')),
                ('feedback_correct', models.TextField(blank=True)),
                ('feedback_incorrect', models.TextField(blank=True)),
                ('question_type', models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_ANSWER', 'Multiple answer')], default='SINGLE_CHOICE', max_length=20)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('assistant_supervisor', 'Assistant/Supervisor'), ('officer', 'Officer'), ('management', 'Management'), ('senior_management', 'Senior Management')], max_length=30)),
                ('pass_threshold', models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('questions_per_attempt', models.PositiveIntegerField(default=15, validators=[django.core.validators.MinValueValidator(1)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_levels', to='accounts.organization')),
            ],
            options={
                'ordering': ['organization', 'name'],
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LevelAssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questions_drawn', models.JSONField(default=list)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))])),
                ('passed', models.BooleanField(default=False)),
                ('assessment_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='levelassessments.assessmentlevel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assessment_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(blank=True, default='', max_length=500)),
                ('is_correct', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='levelassessments.levelquestion')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=150)),
                ('assessment_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_sets', to='levelassessments.assessmentlevel')),
            ],
            options={
                'ordering': ['assessment_level', 'label'],
            },
        ),
        migrations.AddField(
            model_name='levelquestion',
            name='question_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='levelassessments.questionset'),
        ),
        migrations.AddConstraint(
            model_name='levelassessmentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('submitted_at__isnull', True)), fields=('user', 'assessment_level'), name='one_open_level_assessment_attempt_per_user_level'),
        ),
    ]
