# Generated by Django 5.0.14 on 2026-09-05 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelassessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelAssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='levelassessments.levelassessmentattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='levelassessments.levelquestion')),
                ('selected_choices', models.ManyToManyField(blank=True, related_name='selected_in_answers', to='levelassessments.levelchoice')),
            ],
            options={
                'ordering': ['question__order', 'question_id'],
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
