# Generated by Django 5.0.14 on 2026-09-08 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelassessments', '0002_levelassessmentanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentlevel',
            name='name',
            field=models.CharField(choices=[('assistant_supervisor', 'Front-Line Level'), ('officer', 'Officer Level'), ('management', 'Middle Management Level'), ('senior_management', 'Top Management Level')], max_length=30),
        ),
    ]
