# Generated by Django 5.0.14 on 2026-09-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('levelassessments', '0004_seed_org_assessment_levels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentlevel',
            name='pass_threshold',
        ),
        migrations.RemoveField(
            model_name='assessmentlevel',
            name='questions_per_attempt',
        ),
    ]
