# Generated by Django 5.0.14 on 2026-09-15 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('levelassessments', '0005_remove_assessmentlevel_pass_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='levelassessmentattempt',
            name='answers_so_far',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='levelassessmentattempt',
            name='current_question_index',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='levelassessmentattempt',
            name='timer_segment_started_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
