# Generated by Django 5.0.14 on 2026-07-22 02:24

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0002_alter_question_question_text'),
        ('courses', '0005_page_pagerevision_pageprogress'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['page', 'title']},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='course',
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Rich text shown to the learner after answering.'),
        ),
        migrations.AddField(
            model_name='question',
            name='feedback_correct',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='feedback_incorrect',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='question',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='page',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='courses.page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('MULTIPLE_ANSWER', 'Multiple answer'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the blank'), ('MATCHING', 'Matching'), ('ORDERING', 'Ordering'), ('SHORT_ANSWER', 'Short answer'), ('ESSAY', 'Essay')], default='SINGLE_CHOICE', max_length=20),
        ),
    ]
