# Generated by Django 5.0.14 on 2026-07-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0003_alter_quiz_options_remove_quiz_course_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='choice',
            name='match_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='grader_feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='marks_awarded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='text_response',
            field=models.TextField(blank=True, default=''),
        ),
    ]
