# Generated by Django 5.0.14 on 2026-07-28 02:51

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0007_backfill_matching_is_correct'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='category_placements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('MULTIPLE_ANSWER', 'Multiple answer'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the blank'), ('MATCHING', 'Matching'), ('ORDERING', 'Ordering'), ('CATEGORIZE', 'Categorize'), ('SHORT_ANSWER', 'Short answer'), ('ESSAY', 'Essay')], default='SINGLE_CHOICE', max_length=20),
        ),
        migrations.CreateModel(
            name='CategoryBucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buckets', to='assessments.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CategorizeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_text', models.CharField(blank=True, default='', max_length=500)),
                ('item_image', models.ImageField(blank=True, null=True, upload_to='categorize_item_images/', validators=[accounts.validators.validate_image_size])),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorize_items', to='assessments.question')),
                ('correct_bucket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='assessments.categorybucket')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
