# Generated by Django 5.0.14 on 2026-07-28 03:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_quizanswer_category_placements_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('SINGLE_CHOICE', 'Single choice'), ('MULTIPLE_CHOICE', 'Multiple choice'), ('MULTIPLE_ANSWER', 'Multiple answer'), ('TRUE_FALSE', 'True/False'), ('FILL_BLANK', 'Fill in the blank'), ('MATCHING', 'Matching'), ('ORDERING', 'Ordering'), ('CATEGORIZE', 'Categorize'), ('HOTSPOT', 'Hotspot'), ('SHORT_ANSWER', 'Short answer'), ('ESSAY', 'Essay')], default='SINGLE_CHOICE', max_length=20),
        ),
        migrations.CreateModel(
            name='HotspotRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('y', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('width', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('height', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hotspot_regions', to='assessments.question')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='selected_regions',
            field=models.ManyToManyField(blank=True, related_name='selected_in_answers', to='assessments.hotspotregion'),
        ),
    ]
