# Generated by Django 5.0.14 on 2026-07-28 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_alter_question_question_type_hotspotregion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='blank_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='fill_blank_mode',
            field=models.CharField(choices=[('TEXT_INPUT', 'Text input'), ('WORD_BANK', 'Word bank')], default='TEXT_INPUT', max_length=20),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='fill_blank_text',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='word_bank_placements',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='WordBankToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('correct_blank_index', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='word_bank_tokens', to='assessments.question')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
