# Generated by Django 5.0.14 on 2026-08-03 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_choice_blank_index_question_fill_blank_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
