# Generated by Django 5.0.14 on 2026-08-03 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_alter_choice_choice_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorybucket',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='wordbanktoken',
            name='text',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
