# Generated by Django 5.0.14 on 2026-07-21 12:05

import courses.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='content_file',
            field=models.FileField(blank=True, null=True, upload_to='lesson_content/', validators=[courses.validators.validate_lesson_file_size]),
        ),
    ]
