# Generated by Django 5.0.14 on 2026-07-21 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0002_alter_lesson_content_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='organization',
            field=models.ForeignKey(blank=True, help_text='The owning organization for ORGANIZATION-owned courses. Ignored for access control on PLATFORM-owned courses — see CourseAccess instead.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='accounts.organization'),
        ),
        migrations.CreateModel(
            name='CourseAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='courses.course')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_access_grants', to='accounts.organization')),
            ],
            options={
                'ordering': ['-granted_at'],
                'unique_together': {('course', 'organization')},
            },
        ),
    ]
