# Generated by Django 5.0.14 on 2026-07-21 16:04

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_alter_course_organization_courseaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='course_covers/', validators=[accounts.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, validators=[django.core.validators.MaxLengthValidator(10000)]),
        ),
    ]
