# Generated by Django 5.0.14 on 2026-07-22 13:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_delete_page_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_expiry_months',
            field=models.PositiveIntegerField(blank=True, help_text='Months after issuance the certificate expires. Null means it never expires.', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='certificate_pass_threshold',
            field=models.PositiveIntegerField(default=70, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
