# Generated by Django 5.0.14 on 2026-07-22 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_course_certificate_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='align',
            field=models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='CENTER', max_length=10),
        ),
    ]
