# Generated by Django 5.0.14 on 2026-07-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_element_align'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='completion_deadline_days',
            field=models.PositiveIntegerField(blank=True, help_text='Days after enrollment the course should be completed by. Null means no deadline.', null=True),
        ),
    ]
