# Generated by Django 5.0.14 on 2026-07-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_completion_deadline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='slide_type',
            field=models.CharField(choices=[('CONTENT', 'Content'), ('QUIZ', 'Quiz'), ('ASSIGNMENT', 'Assignment'), ('SCENARIO', 'Scenario')], default='CONTENT', max_length=20),
        ),
    ]
