# Generated by Django 5.0.14 on 2026-07-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0013_alter_slide_slide_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='layout',
            field=models.CharField(choices=[('STACKED', 'Stacked'), ('IMAGE_LEFT', 'Image left'), ('IMAGE_RIGHT', 'Image right')], default='STACKED', max_length=20),
        ),
    ]
