# Generated by Django 5.0.14 on 2026-07-28 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_slide_layout'),
    ]

    operations = [
        migrations.CreateModel(
            name='SlideTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('background_css', models.CharField(max_length=255)),
                ('text_color', models.CharField(max_length=20)),
                ('accent_color', models.CharField(max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='courses.slidetemplate'),
        ),
        migrations.AddField(
            model_name='slide',
            name='template_override',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slide_overrides', to='courses.slidetemplate'),
        ),
    ]
