# Generated by Django 5.0.14 on 2026-08-05 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0016_seed_slide_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='image_column_width',
            field=models.CharField(choices=[('COMPACT', 'Compact'), ('STANDARD', 'Standard'), ('WIDE', 'Wide')], default='STANDARD', max_length=20),
        ),
    ]
