# Generated by Django 5.0.14 on 2026-08-06 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0002_certificatetemplate'),
        ('courses', '0018_alter_course_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='certificates.certificatetemplate'),
        ),
    ]
