# Generated by Django 5.0.14 on 2026-08-06 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_course_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_demo_available',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DemoLessonAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_lesson_access', to='courses.course')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_access_entries', to='courses.lesson')),
            ],
            options={
                'ordering': ['lesson__order'],
                'unique_together': {('course', 'lesson')},
            },
        ),
    ]
