# Generated by Django 5.0.14 on 2026-08-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0020_course_is_demo_available_demolessonaccess'),
        ('dialogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='dialogue_character_left',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dialogue.character'),
        ),
        migrations.AddField(
            model_name='element',
            name='dialogue_character_right',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dialogue.character'),
        ),
        migrations.AddField(
            model_name='element',
            name='dialogue_lines',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='element',
            name='dialogue_scene',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dialogue.scene'),
        ),
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[('TEXT', 'Text'), ('IMAGE', 'Image'), ('VIDEO_AUDIO', 'Video/Audio'), ('BREAKOUT_IMAGE', 'Breakout image'), ('QUOTE', 'Quote'), ('FILE_DOWNLOAD', 'File download'), ('EMBED', 'Embed'), ('PRESENTATION_PDF', 'Presentation/PDF'), ('DIALOGUE', 'Dialogue')], default='TEXT', max_length=20),
        ),
    ]
