# Generated by Django 5.0.14 on 2026-09-06 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_element_dialogue_character_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='cloned_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clones', to='courses.course'),
        ),
    ]
