# Generated by Django 5.0.14 on 2026-09-12 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_normalize_module_and_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='minimum_assessment_level',
            field=models.CharField(blank=True, choices=[('assistant_supervisor', 'Front-Line Level'), ('officer', 'Officer Level'), ('management', 'Middle Management Level'), ('senior_management', 'Top Management Level')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='path_order',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
