# Generated by Django 5.0.14 on 2026-09-14 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_course_minimum_assessment_level_course_path_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='certificate_pass_threshold',
        ),
    ]
