# Generated by Django 5.0.14 on 2026-09-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_remove_course_certificate_pass_threshold'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='retake_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
