# Generated by Django 5.0.14 on 2026-09-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_enrollment_retake_count'),
        ('levelassessments', '0006_levelassessmentattempt_answers_so_far_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LevelCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('assessment_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='levelassessments.assessmentlevel')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_assignments', to='courses.course')),
            ],
            options={
                'ordering': ['assessment_level', 'order', 'id'],
                'unique_together': {('assessment_level', 'course')},
            },
        ),
    ]
