# Generated by Django 5.0.14 on 2026-07-22 02:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0005_page_pagerevision_pageprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructions_json', models.JSONField(blank=True, default=list, help_text='BlockNote document.')),
                ('submission_type', models.CharField(choices=[('FILE_UPLOAD', 'File upload'), ('TEXT', 'Text')], default='FILE_UPLOAD', max_length=20)),
                ('max_marks', models.PositiveIntegerField(default=100)),
                ('due_offset_days', models.PositiveIntegerField(blank=True, help_text='Days after enrollment the assignment is due. Null means no due date.', null=True)),
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='courses.page')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='assignment_submissions/')),
                ('text_response', models.TextField(blank=True)),
                ('marks_awarded', models.PositiveIntegerField(blank=True, null=True)),
                ('grader_feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
