# Generated by Django 5.0.14 on 2026-08-15 13:46

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('CUSTOMER', 'Customer'), ('TELLER', 'Teller'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('BRANCH_MANAGER', 'Branch Manager'), ('OTHER', 'Other')], max_length=20)),
                ('avatar_image', models.FileField(upload_to='character_avatars/', validators=[accounts.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scene_type', models.CharField(choices=[('FRONT_OFFICE', 'Front office'), ('BACK_OFFICE', 'Back office')], max_length=20)),
                ('background_image', models.FileField(upload_to='scene_backgrounds/', validators=[accounts.validators.validate_image_size, django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'svg'])])),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
