# Generated by Django 5.0.14 on 2026-08-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_seed_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='certificates_earned_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
