# Generated by Django 5.0.14 on 2026-08-08 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_backfill_certificates_earned_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='unlock_condition',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
