# Generated by Django 5.0.14 on 2026-09-05 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_seed_level_assessment_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboardentry',
            name='level_assessments_passed_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
