# Generated by Django 5.0.14 on 2026-07-28 05:38

import accounts.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0013_alter_slide_slide_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScenarioAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path_taken', models.JSONField(blank=True, default=list)),
                ('reached_recommended_ending', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_attempts', to='courses.enrollment')),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_attempts', to='courses.slide')),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_key', models.SlugField()),
                ('prompt', models.TextField(blank=True, default='')),
                ('prompt_image', models.ImageField(blank=True, null=True, upload_to='scenario_node_images/', validators=[accounts.validators.validate_image_size])),
                ('is_start', models.BooleanField(default=False)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_nodes', to='courses.slide')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('slide', 'node_key')},
            },
        ),
        migrations.CreateModel(
            name='ScenarioChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500)),
                ('feedback_text', models.TextField(blank=True, default='')),
                ('is_recommended', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('next_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_choices', to='scenarios.scenarionode')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='scenarios.scenarionode')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
