# Generated by Django 5.0.14 on 2026-08-03 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenariochoice',
            name='choice_text',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
