# Generated by Django 5.0.14 on 2026-09-05 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0004_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('COURSE_CREATED', 'Course created'), ('CERTIFICATE_GENERATED', 'Certificate generated'), ('ENROLLMENT_CREATED', 'Enrollment created'), ('ENROLLMENT_UPDATED', 'Enrollment updated'), ('DEMO_USER_CREATED', 'Demo user created'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('ORGANIZATION_CREATED', 'Organization created'), ('ORG_ADMIN_CREATED', 'Organization admin created'), ('LEVEL_QUESTIONS_IMPORTED', 'Level assessment questions imported')], max_length=30),
        ),
    ]
