# Generated by Django 5.0.14 on 2026-09-16 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0011_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('COURSE_CREATED', 'Course created'), ('COURSE_CLONED', 'Course cloned'), ('COURSE_DUPLICATED', 'Course duplicated'), ('CERTIFICATE_GENERATED', 'Certificate generated'), ('ENROLLMENT_CREATED', 'Enrollment created'), ('ENROLLMENT_UPDATED', 'Enrollment updated'), ('DEMO_USER_CREATED', 'Demo user created'), ('PASSWORD_RESET_COMPLETED', 'Password reset completed'), ('ORGANIZATION_CREATED', 'Organization created'), ('ORGANIZATION_DELETED', 'Organization deleted'), ('LEARNER_DELETED', 'Learner deleted'), ('ORG_ADMIN_CREATED', 'Organization admin created'), ('LEVEL_QUESTIONS_IMPORTED', 'Level assessment questions imported'), ('LEVEL_QUESTION_UPDATED', 'Level assessment question updated'), ('LEVEL_QUESTION_DELETED', 'Level assessment question deleted'), ('STAFF_ENROLLED', 'Staff learner enrolled'), ('STAFF_DEACTIVATED', 'Staff learner deactivated'), ('STAFF_REACTIVATED', 'Staff learner reactivated')], max_length=30),
        ),
    ]
