# Generated by Django 5.0.14 on 2026-08-06 13:03

import accounts.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certificates', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='certificate_templates/backgrounds/', validators=[accounts.validators.validate_image_size])),
                ('is_default', models.BooleanField(default=False, help_text='The platform-wide fallback used by any course without its own certificate_template set.')),
                ('staff_name_x_percent', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('staff_name_y_percent', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('staff_name_font_size', models.PositiveIntegerField(default=60)),
                ('staff_name_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #E9B730.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('staff_name_font_file', models.FileField(blank=True, null=True, upload_to='certificate_templates/fonts/')),
                ('staff_name_text_align', models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='CENTER', max_length=6)),
                ('course_name_x_percent', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course_name_y_percent', models.FloatField(default=60.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('course_name_font_size', models.PositiveIntegerField(default=32)),
                ('course_name_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #E9B730.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('course_name_font_file', models.FileField(blank=True, null=True, upload_to='certificate_templates/fonts/')),
                ('course_name_text_align', models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='CENTER', max_length=6)),
                ('issue_date_x_percent', models.FloatField(default=50.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('issue_date_y_percent', models.FloatField(default=70.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('issue_date_font_size', models.PositiveIntegerField(default=24)),
                ('issue_date_color', models.CharField(default='#000000', max_length=7, validators=[django.core.validators.RegexValidator(message='Enter a valid hex color, e.g. #E9B730.', regex='^#[0-9A-Fa-f]{6}$')])),
                ('issue_date_font_file', models.FileField(blank=True, null=True, upload_to='certificate_templates/fonts/')),
                ('issue_date_text_align', models.CharField(choices=[('LEFT', 'Left'), ('CENTER', 'Center'), ('RIGHT', 'Right')], default='CENTER', max_length=6)),
                ('qr_code_x_percent', models.FloatField(default=85.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qr_code_y_percent', models.FloatField(default=85.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('qr_code_size_percent', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
