# Generated by Django 5.0.14 on 2026-09-05 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_assessment_level_user_branch_department_and_more'),
        ('certificates', '0003_seed_default_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certificate_templates', to='accounts.organization'),
        ),
        migrations.AlterField(
            model_name='certificatetemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='The platform-wide fallback used by any course/organization without their own certificate template. Only meaningful (and only settable) on a platform-level template — organization must be empty.'),
        ),
        migrations.AddConstraint(
            model_name='certificatetemplate',
            constraint=models.UniqueConstraint(condition=models.Q(('organization__isnull', False)), fields=('organization',), name='one_certificate_template_per_organization'),
        ),
    ]
